name: Run experiments

on: [push, pull_request]

jobs:
  experiments:
    runs-on: ubuntu-latest
    env:
      GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Download and Extract Build Validation Scripts
        run: |
          curl -s -L -O https://github.com/gradle/gradle-enterprise-build-validation-scripts/releases/download/v1.0/gradle-enterprise-gradle-build-validation-1.0.zip
          unzip -q -o gradle-enterprise-gradle-build-validation-1.0.zip
      - uses: ./.github/actions/exp1
        with:
          repositoryUrl: 'https://github.com/gradle/gradle-build-scan-quickstart'
          branch: 'master'
          task: 'build'
