name: Run experiments

on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
  experiments:
    runs-on: ubuntu-latest
    env:
      GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
    strategy:
      matrix:
        include:
          - project: 'gradle-build-scan-quickstart'
            repositoryUrl: 'https://github.com/gradle/gradle-build-scan-quickstart'
            branch: 'master'
            task: 'build'
            java-version: '11'
          - project: 'gradle'
            repositoryUrl: 'https://github.com/gradle/gradle'
            branch: 'master'
            task: 'allVersionsCrossVersionTest'
            java-version: '11'
          - project: 'kotlin'
            repositoryUrl: 'https://github.com/JetBrains/kotlin'
            branch: 'master'
            task: 'install'
            java-version: '11'
          - project: 'spring-framework'
            repositoryUrl: 'https://github.com/spring-projects/spring-framework'
            branch: 'main'
            task: 'build'
            java-version: '17'
          - project: 'junit5'
            repositoryUrl: 'https://github.com/junit-team/junit5'
            branch: 'main'
            task: 'assemble'
            java-version: '17'
          - project: 'ratpack'
            repositoryUrl: 'https://github.com/ratpack/ratpack'
            branch: 'master'
            task: '"build -x:ratpack-core:test"'
            java-version: '11'
          - project: 'spock'
            repositoryUrl: 'https://github.com/spockframework/spock'
            branch: 'master'
            task: '"build codeCoverageReport"'
            java-version: '11'
          - project: 'micrometer'
            repositoryUrl: 'https://github.com/micrometer-metrics/micrometer'
            branch: 'main'
            task: 'build'
            java-version: '11'
          - project: 'micronaut'
            repositoryUrl: 'https://github.com/micronaut-projects/micronaut-build'
            branch: 'master'
            task: 'check'
            java-version: '11'
          - project: 'testcontainers'
            repositoryUrl: 'https://github.com/testcontainers/testcontainers-java'
            branch: 'master'
            task: ':mariadb:check'
            java-version: '11'
          - project: 'hibernate-orm'
            repositoryUrl: 'https://github.com/hibernate/hibernate-orm'
            branch: 'main'
            task: 'check'
            java-version: '11'
          - project: 'grails-core'
            repositoryUrl: 'https://github.com/grails/grails-core'
            branch: '5.1.x'
            task: 'build'
            java-version: '11'
          - project: 'androidx'
            repositoryUrl: 'https://github.com/androidx/androidx'
            branch: 'androidx-main'
            task: '"buildOnServer zipTestConfigsWithApks test"'
            java-version: '11'
          - project: 'openrewrite'
            repositoryUrl: 'https://github.com/openrewrite/rewrite-concourse'
            branch: 'main'
            task: 'build'
            java-version: '11'
          - project: 'opentelemetry'
            repositoryUrl: 'https://github.com/open-telemetry/opentelemetry-java-instrumentation'
            branch: 'main'
            task: 'assemble'
            java-version: '11'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
      - name: Download and Extract Build Validation Scripts
        run: |
          curl -s -L -O https://github.com/gradle/gradle-enterprise-build-validation-scripts/releases/download/v1.0/gradle-enterprise-gradle-build-validation-1.0.zip
          unzip -q -o gradle-enterprise-gradle-build-validation-1.0.zip
      - uses: ./.github/actions/exp1
        with:
          repositoryUrl: ${{ matrix.repositoryUrl }}
          branch: ${{ matrix.branch }}
          task: ${{ matrix.task }}
      - uses: ./.github/actions/exp2
        with:
          repositoryUrl: ${{ matrix.repositoryUrl }}
          branch: ${{ matrix.branch }}
          task: ${{ matrix.task }}
      - uses: ./.github/actions/exp3
        with:
          repositoryUrl: ${{ matrix.repositoryUrl }}
          branch: ${{ matrix.branch }}
          task: ${{ matrix.task }}
