name: XWiki

on:
  workflow_dispatch:

env:
  DEVELOCITY_URL: "https://ge.solutions-team.gradle.com"
  GIT_REPO: "https://github.com/xwiki/xwiki-commons"
  GOALS: "validate"
  ARGS: "-B"

jobs:
  Experiment:

    strategy:
      fail-fast: false
      matrix:
        include:
          - experimentId: 1
          - experimentId: 2

    runs-on: ubuntu-latest
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.12.0
        with:
          checkout-fetch-depth: 0
          java-version: 17
          java-distribution: temurin
          maven-version: 3.9.6
      - name: Configure Maven settings
        run: >
          echo '<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                                https://maven.apache.org/xsd/settings-1.0.0.xsd">
              <profiles>
                <profile>
                  <id>xwiki</id>
                  <repositories>
                    <repository>
                      <id>xwiki-snapshots</id>
                      <name>XWiki Nexus Snapshot Repository Proxy</name>
                      <url>https://nexus.xwiki.org/nexus/content/groups/public-snapshots</url>
                      <releases><enabled>false</enabled></releases>
                      <snapshots><enabled>true</enabled></snapshots>
                    </repository>
                    <repository>
                      <id>xwiki-releases</id>
                      <name>XWiki Nexus Releases Repository Proxy</name>
                      <url>https://nexus.xwiki.org/nexus/content/groups/public</url>
                      <releases><enabled>true</enabled></releases>
                      <snapshots><enabled>false</enabled></snapshots>
                    </repository>
                  </repositories>
                  <pluginRepositories>
                    <pluginRepository>
                      <id>xwiki-snapshots</id>
                      <name>XWiki Nexus Plugin Snapshot Repository Proxy</name>
                      <url>https://nexus.xwiki.org/nexus/content/groups/public-snapshots</url>
                      <releases><enabled>false</enabled></releases>
                      <snapshots><enabled>true</enabled></snapshots>
                    </pluginRepository>
                    <pluginRepository>
                      <id>xwiki-releases</id>
                      <name>XWiki Nexus Plugin Releases Repository Proxy</name>
                      <url>https://nexus.xwiki.org/nexus/content/groups/public</url>
                      <releases><enabled>true</enabled></releases>
                      <snapshots><enabled>false</enabled></snapshots>
                    </pluginRepository>
                  </pluginRepositories>
                </profile>
              </profiles>
              <activeProfiles>
                  <activeProfile>xwiki</activeProfile>
              </activeProfiles>
            </settings>' > ~/.m2/settings.xml
      - name: Download latest version of the validation scripts
        uses: gradle/gradle-enterprise-build-validation-scripts/.github/actions/maven/download@fd3a175265f052701b401f7467c086c13067f59b
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run experiment 1
        id: run2
        uses: gradle/gradle-enterprise-build-validation-scripts/.github/actions/maven/experiment-1@fd3a175265f052701b401f7467c086c13067f59b
        env:
          DEVELOCITY_ACCESS_KEY: "${{ secrets.DV_SOLUTIONS_ACCESS_KEY }}"
        with:
          gitRepo: ${{ env.GIT_REPO }}
          goals: ${{ env.GOALS }}
          args: ${{ env.ARGS }}
          develocityUrl: ${{ env.DEVELOCITY_URL }}
          failIfNotFullyCacheable: true
        if: matrix.experimentId == 1
      - name: Run experiment 2
        uses: gradle/gradle-enterprise-build-validation-scripts/.github/actions/maven/experiment-2@fd3a175265f052701b401f7467c086c13067f59b
        env:
          DEVELOCITY_ACCESS_KEY: "${{ secrets.DV_SOLUTIONS_ACCESS_KEY }}"
        with:
          gitRepo: ${{ env.GIT_REPO }}
          goals: ${{ env.GOALS }}
          args: ${{ env.ARGS }}
          develocityUrl: ${{ env.DEVELOCITY_URL }}
          failIfNotFullyCacheable: true
        if: matrix.experimentId == 2
      - name: Fill GitHub summary and outputs
        id: run
        if: always()
        run: |
          echo "1st build = ${{ steps.run2.outputs.buildScanFirstBuild }}"
          echo "2nd build = ${{ steps.run2.outputs.buildScanSecondBuild }}"
