name: XWiki

on:
  workflow_dispatch:

env:
  DEVELOCITY_URL: "https://ge.solutions-team.gradle.com"
  GIT_REPO: "https://github.com/xwiki/xwiki-commons"
  GOALS: "install"
  ARGS: "-B"

jobs:
  Experiment:

    strategy:
      fail-fast: false
      matrix:
        include:
          - experimentId: 1
          - experimentId: 2

    runs-on: ubuntu-latest
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.12.0
        with:
          checkout-fetch-depth: 0
          java-version: 17
          java-distribution: temurin
          maven-version: 3.9.6
      - name: Configure Maven settings
        run: >
          echo '<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                                https://maven.apache.org/xsd/settings-1.0.0.xsd">
              <profiles>
                <profile>
                  <id>xwiki</id>
                  <repositories>
                    <repository>
                      <id>xwiki-snapshots</id>
                      <name>XWiki Nexus Snapshot Repository Proxy</name>
                      <url>https://nexus.xwiki.org/nexus/content/groups/public-snapshots</url>
                      <releases><enabled>false</enabled></releases>
                      <snapshots><enabled>true</enabled></snapshots>
                    </repository>
                    <repository>
                      <id>xwiki-releases</id>
                      <name>XWiki Nexus Releases Repository Proxy</name>
                      <url>https://nexus.xwiki.org/nexus/content/groups/public</url>
                      <releases><enabled>true</enabled></releases>
                      <snapshots><enabled>false</enabled></snapshots>
                    </repository>
                  </repositories>
                  <pluginRepositories>
                    <pluginRepository>
                      <id>xwiki-snapshots</id>
                      <name>XWiki Nexus Plugin Snapshot Repository Proxy</name>
                      <url>https://nexus.xwiki.org/nexus/content/groups/public-snapshots</url>
                      <releases><enabled>false</enabled></releases>
                      <snapshots><enabled>true</enabled></snapshots>
                    </pluginRepository>
                    <pluginRepository>
                      <id>xwiki-releases</id>
                      <name>XWiki Nexus Plugin Releases Repository Proxy</name>
                      <url>https://nexus.xwiki.org/nexus/content/groups/public</url>
                      <releases><enabled>true</enabled></releases>
                      <snapshots><enabled>false</enabled></snapshots>
                    </pluginRepository>
                  </pluginRepositories>
                </profile>
              </profiles>
              <activeProfiles>
                  <activeProfile>xwiki</activeProfile>
              </activeProfiles>
            </settings>' > ~/.m2/settings.xml
      - name: Download latest version of the validation scripts
        uses: gradle/gradle-enterprise-build-validation-scripts/.github/actions/maven/download@actions-stable
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
#      - name: Run experiment 1
#        uses: gradle/gradle-enterprise-build-validation-scripts/.github/actions/maven/experiment-1@8d29d063790dc8ed7326dbb5c681d8f5892212d7
#        env:
#          DEVELOCITY_ACCESS_KEY: "${{ secrets.DV_SOLUTIONS_ACCESS_KEY }}"
#        with:
#          gitRepo: ${{ env.GIT_REPO }}
#          goals: ${{ env.GOALS }}
#          args: ${{ env.ARGS }}
#          develocityUrl: ${{ env.DEVELOCITY_URL }}
#          failIfNotFullyCacheable: true
#        if: matrix.experimentId == 1
      - name: Run experiment 2 - 0
        uses: gradle/gradle-enterprise-build-validation-scripts/.github/actions/maven/experiment-2@fd4fdad0554b90618e2eb9e73f342579695d187b
        env:
          DEVELOCITY_ACCESS_KEY: "${{ secrets.DV_SOLUTIONS_ACCESS_KEY }}"
        with:
          gitRepo: ${{ env.GIT_REPO }}
          goals: ${{ env.GOALS }}
          args: ${{ env.ARGS }}
          develocityUrl: ${{ env.DEVELOCITY_URL }}
          failIfNotFullyCacheable: true
#        if: matrix.experimentId == 2
      - name: Run experiment 2 - 0
        uses: gradle/gradle-enterprise-build-validation-scripts/.github/actions/maven/experiment-2@fd4fdad0554b90618e2eb9e73f342579695d187b
        env:
          DEVELOCITY_ACCESS_KEY: "${{ secrets.DV_SOLUTIONS_ACCESS_KEY }}"
        with:
          gitRepo: ${{ env.GIT_REPO }}
          goals: ${{ env.GOALS }}
          args: ${{ env.ARGS }}
          develocityUrl: ${{ env.DEVELOCITY_URL }}
          failIfNotFullyCacheable: true
          testCode: 0
        if: always()
      - name: Run experiment 2 - 1
        uses: gradle/gradle-enterprise-build-validation-scripts/.github/actions/maven/experiment-2@fd4fdad0554b90618e2eb9e73f342579695d187b
        env:
          DEVELOCITY_ACCESS_KEY: "${{ secrets.DV_SOLUTIONS_ACCESS_KEY }}"
        with:
          gitRepo: ${{ env.GIT_REPO }}
          goals: ${{ env.GOALS }}
          args: ${{ env.ARGS }}
          develocityUrl: ${{ env.DEVELOCITY_URL }}
          failIfNotFullyCacheable: true
          testCode: 1
        if: always()
      - name: Run experiment 2 - 2
        uses: gradle/gradle-enterprise-build-validation-scripts/.github/actions/maven/experiment-2@fd4fdad0554b90618e2eb9e73f342579695d187b
        env:
          DEVELOCITY_ACCESS_KEY: "${{ secrets.DV_SOLUTIONS_ACCESS_KEY }}"
        with:
          gitRepo: ${{ env.GIT_REPO }}
          goals: ${{ env.GOALS }}
          args: ${{ env.ARGS }}
          develocityUrl: ${{ env.DEVELOCITY_URL }}
          failIfNotFullyCacheable: true
          testCode: 2
        if: always()
      - name: Run experiment 2 - 3
        uses: gradle/gradle-enterprise-build-validation-scripts/.github/actions/maven/experiment-2@fd4fdad0554b90618e2eb9e73f342579695d187b
        env:
          DEVELOCITY_ACCESS_KEY: "${{ secrets.DV_SOLUTIONS_ACCESS_KEY }}"
        with:
          gitRepo: ${{ env.GIT_REPO }}
          goals: ${{ env.GOALS }}
          args: ${{ env.ARGS }}
          develocityUrl: ${{ env.DEVELOCITY_URL }}
          failIfNotFullyCacheable: true
          testCode: 3
        if: always()
      - name: Run experiment 2 - 4
        uses: gradle/gradle-enterprise-build-validation-scripts/.github/actions/maven/experiment-2@fd4fdad0554b90618e2eb9e73f342579695d187b
        env:
          DEVELOCITY_ACCESS_KEY: "${{ secrets.DV_SOLUTIONS_ACCESS_KEY }}"
        with:
          gitRepo: ${{ env.GIT_REPO }}
          goals: ${{ env.GOALS }}
          args: ${{ env.ARGS }}
          develocityUrl: ${{ env.DEVELOCITY_URL }}
          failIfNotFullyCacheable: true
          testCode: 4
        if: always()
      - name: Run experiment 2 - 100
        uses: gradle/gradle-enterprise-build-validation-scripts/.github/actions/maven/experiment-2@fd4fdad0554b90618e2eb9e73f342579695d187b
        env:
          DEVELOCITY_ACCESS_KEY: "${{ secrets.DV_SOLUTIONS_ACCESS_KEY }}"
        with:
          gitRepo: ${{ env.GIT_REPO }}
          goals: ${{ env.GOALS }}
          args: ${{ env.ARGS }}
          develocityUrl: ${{ env.DEVELOCITY_URL }}
          failIfNotFullyCacheable: true
          testCode: 100
        if: always()
